### ISSUE TITLE
Running pserve with production.ini fails

### ISSUE THREAD

**Issue by fordanic** [VoteIT/voteit.core#368]
A bit unclear about where to post this but anyhow. Made use of the buildout found here https://github.com/VoteIT/stf_buildout and replace stf references with relevant values. When running `pserve` on `production.ini` it fails with 
```
ConfigParser.InterpolationMissingOptionError: Error in file /home/dafor/srv/pingstlkp_buildout/etc/production.ini: Bad value substitution:
        section: [server:main]
        option : unix_socket
        key    : process_num
        rawval : %(here)s/../var/waitress-%(process_num)s.sock
```
Running `pserve` on `development.ini` works as expected. Any suggestions on what to do?

**Comment by robinharms** [comment]
It fails since you're missing process_num, in that instance it's ment to be started with
pserve <inifile> process_num=<somenum>

supervisor does that automatically so it's possible to scale up instances.

Please don't use issue-reporting for support questions though. If you want to try out voteit, see mote.voteit.se or voteit.se
